# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x10treehacks.common\"\xb2\x01\n\x0fInferenceParams\x12\x12\n\nmax_tokens\x18\x01 \x01(\x05\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\r\n\x05top_p\x18\x03 \x01(\x02\x12\r\n\x05top_k\x18\x04 \x01(\x05\x12\x16\n\x0estop_sequences\x18\x05 \x03(\t\x12\x0c\n\x04seed\x18\x06 \x01(\x05\x12\x14\n\x0c\x64raft_tokens\x18\x07 \x01(\x05\x12\x1c\n\x14\x61\x63\x63\x65ptance_threshold\x18\x08 \x01(\x02\"8\n\x05Token\x12\x10\n\x08token_id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0f\n\x07logprob\x18\x03 \x01(\x02\"J\n\rTokenSequence\x12\'\n\x06tokens\x18\x01 \x03(\x0b\x32\x17.treehacks.common.Token\x12\x10\n\x08logprobs\x18\x02 \x03(\x02\"B\n\tModelInfo\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"\x93\x01\n\rResourceStats\x12\x17\n\x0fgpu_utilization\x18\x01 \x01(\x02\x12\x19\n\x11memory_used_bytes\x18\x02 \x01(\x03\x12\x1a\n\x12memory_total_bytes\x18\x03 \x01(\x03\x12\x17\n\x0f\x61\x63tive_requests\x18\x04 \x01(\x05\x12\x19\n\x11tokens_per_second\x18\x05 \x01(\x02*\x8e\x01\n\nStatusCode\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n\x0eSTATUS_SUCCESS\x10\x01\x12\x12\n\x0eSTATUS_PENDING\x10\x02\x12\x11\n\rSTATUS_FAILED\x10\x03\x12\x12\n\x0eSTATUS_TIMEOUT\x10\x04\x12\x1d\n\x19STATUS_RESOURCE_EXHAUSTED\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSCODE']._serialized_start=568
  _globals['_STATUSCODE']._serialized_end=710
  _globals['_INFERENCEPARAMS']._serialized_start=35
  _globals['_INFERENCEPARAMS']._serialized_end=213
  _globals['_TOKEN']._serialized_start=215
  _globals['_TOKEN']._serialized_end=271
  _globals['_TOKENSEQUENCE']._serialized_start=273
  _globals['_TOKENSEQUENCE']._serialized_end=347
  _globals['_MODELINFO']._serialized_start=349
  _globals['_MODELINFO']._serialized_end=415
  _globals['_RESOURCESTATS']._serialized_start=418
  _globals['_RESOURCESTATS']._serialized_end=565
# @@protoc_insertion_point(module_scope)
