# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import speculative_decoding_pb2 as speculative__decoding__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in speculative_decoding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DraftNodeServiceStub(object):
    """Service running on draft nodes (weak GPUs) - receives requests from router
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteInference = channel.unary_unary(
                '/treehacks.speculative.DraftNodeService/ExecuteInference',
                request_serializer=speculative__decoding__pb2.InferenceJobRequest.SerializeToString,
                response_deserializer=speculative__decoding__pb2.InferenceJobResponse.FromString,
                _registered_method=True)
        self.StreamInference = channel.unary_stream(
                '/treehacks.speculative.DraftNodeService/StreamInference',
                request_serializer=speculative__decoding__pb2.InferenceJobRequest.SerializeToString,
                response_deserializer=speculative__decoding__pb2.InferenceStreamChunk.FromString,
                _registered_method=True)


class DraftNodeServiceServicer(object):
    """Service running on draft nodes (weak GPUs) - receives requests from router
    """

    def ExecuteInference(self, request, context):
        """Execute inference request with speculative decoding
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInference(self, request, context):
        """Stream inference results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DraftNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteInference': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteInference,
                    request_deserializer=speculative__decoding__pb2.InferenceJobRequest.FromString,
                    response_serializer=speculative__decoding__pb2.InferenceJobResponse.SerializeToString,
            ),
            'StreamInference': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInference,
                    request_deserializer=speculative__decoding__pb2.InferenceJobRequest.FromString,
                    response_serializer=speculative__decoding__pb2.InferenceStreamChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'treehacks.speculative.DraftNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('treehacks.speculative.DraftNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DraftNodeService(object):
    """Service running on draft nodes (weak GPUs) - receives requests from router
    """

    @staticmethod
    def ExecuteInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treehacks.speculative.DraftNodeService/ExecuteInference',
            speculative__decoding__pb2.InferenceJobRequest.SerializeToString,
            speculative__decoding__pb2.InferenceJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/treehacks.speculative.DraftNodeService/StreamInference',
            speculative__decoding__pb2.InferenceJobRequest.SerializeToString,
            speculative__decoding__pb2.InferenceStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VerificationServiceStub(object):
    """Service running on powerful workers - called by draft nodes for verification
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyDraft = channel.unary_unary(
                '/treehacks.speculative.VerificationService/VerifyDraft',
                request_serializer=speculative__decoding__pb2.VerificationRequest.SerializeToString,
                response_deserializer=speculative__decoding__pb2.VerificationResponse.FromString,
                _registered_method=True)
        self.BatchVerify = channel.unary_unary(
                '/treehacks.speculative.VerificationService/BatchVerify',
                request_serializer=speculative__decoding__pb2.BatchVerificationRequest.SerializeToString,
                response_deserializer=speculative__decoding__pb2.BatchVerificationResponse.FromString,
                _registered_method=True)


class VerificationServiceServicer(object):
    """Service running on powerful workers - called by draft nodes for verification
    """

    def VerifyDraft(self, request, context):
        """Verify draft tokens with the powerful model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchVerify(self, request, context):
        """Batch verification for efficiency
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyDraft,
                    request_deserializer=speculative__decoding__pb2.VerificationRequest.FromString,
                    response_serializer=speculative__decoding__pb2.VerificationResponse.SerializeToString,
            ),
            'BatchVerify': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchVerify,
                    request_deserializer=speculative__decoding__pb2.BatchVerificationRequest.FromString,
                    response_serializer=speculative__decoding__pb2.BatchVerificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'treehacks.speculative.VerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('treehacks.speculative.VerificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VerificationService(object):
    """Service running on powerful workers - called by draft nodes for verification
    """

    @staticmethod
    def VerifyDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treehacks.speculative.VerificationService/VerifyDraft',
            speculative__decoding__pb2.VerificationRequest.SerializeToString,
            speculative__decoding__pb2.VerificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchVerify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/treehacks.speculative.VerificationService/BatchVerify',
            speculative__decoding__pb2.BatchVerificationRequest.SerializeToString,
            speculative__decoding__pb2.BatchVerificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
